(MainThread) 201207_20:32:27.354 ERROR wrapper.py:56 ERROR -1 2104 Market data farm connection is OK:usfarm.nj
(MainThread) 201207_20:32:27.355 ERROR wrapper.py:56 ERROR -1 2104 Market data farm connection is OK:usfuture
(MainThread) 201207_20:32:27.356 ERROR wrapper.py:56 ERROR -1 2104 Market data farm connection is OK:cashfarm
(MainThread) 201207_20:32:27.357 ERROR wrapper.py:56 ERROR -1 2104 Market data farm connection is OK:usopt
(MainThread) 201207_20:32:27.357 ERROR wrapper.py:56 ERROR -1 2104 Market data farm connection is OK:usfarm
(MainThread) 201207_20:32:27.358 ERROR wrapper.py:56 ERROR -1 2106 HMDS data farm connection is OK:euhmds
(MainThread) 201207_20:32:27.361 ERROR wrapper.py:56 ERROR -1 2106 HMDS data farm connection is OK:cashhmds
(MainThread) 201207_20:32:27.362 ERROR wrapper.py:56 ERROR -1 2106 HMDS data farm connection is OK:ushmds
(MainThread) 201207_20:32:27.362 ERROR wrapper.py:56 ERROR -1 2158 Sec-def data farm connection is OK:secdefnj
(MainThread) 201207_20:32:27.528 ERROR wrapper.py:56 ERROR 4103 162 Historical Market Data Service error message:No market data permissions for BATEDE, CHIXDE, DXEDE, EBS, FWB, GETTEX, IBIS, SWB, TGATE, TRQXDE STK
(Thread-1) 201207_20:32:27.960 ERROR reader.py:52 unhandled exception in EReader thread
Traceback (most recent call last):
  File "C:\Users\jsidd\AppData\Roaming\Python\Python38\site-packages\ibapi\reader.py", line 34, in run
    data = self.conn.recvMsg()
  File "C:\Users\jsidd\AppData\Roaming\Python\Python38\site-packages\ibapi\connection.py", line 99, in recvMsg
    buf = self._recvAllMsg()
  File "C:\Users\jsidd\AppData\Roaming\Python\Python38\site-packages\ibapi\connection.py", line 119, in _recvAllMsg
    buf = self.socket.recv(4096)
OSError: [WinError 10038] An operation was attempted on something that is not a socket
